# Generated by Django 4.2.13 on 2024-06-24 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_tag_comment_newsarticle_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsarticle",
            options={"ordering": ["-pub_date"]},
        ),
    ]
