# Generated by Django 5.0.7 on 2024-07-15 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Resolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("positive_action", models.CharField(max_length=200)),
                ("trigger", models.CharField(max_length=200)),
                ("goal", models.CharField(max_length=200)),
                ("incentive", models.CharField(max_length=200)),
                ("negative_action", models.CharField(max_length=200)),
                (
                    "cause",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resolutions.cause",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resolutions.role",
                    ),
                ),
            ],
        ),
    ]
