# Generated by Django 5.0.7 on 2024-09-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resolutions", "0002_remove_resolution_cause_resolution_causes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
