# Generated by Django 5.0.7 on 2025-06-26 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resolutions", "0003_alter_role_options_alter_role_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="resolution",
            name="label",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="resolution",
            name="related_resolutions",
            field=models.ManyToManyField(blank=True, to="resolutions.resolution"),
        ),
        migrations.AddField(
            model_name="resolution",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="resolutions.domain",
            ),
        ),
    ]
